spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AirbnbDB1
    username: AirbnbAdmin
    password: Temp@123

  jpa:
    hibernate:
      ddl-auto: create  # create / create-drop / validate also possible
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#logging:
#  level:
##    root: DEBUG
#    com.example.Week1Introduction.Week_1_.Introduction: DEBUG

jwt:
  secretKey: qwertyuioplkjhgfdsazxcvbnm1234567890qwertyuioplkjhgfdsazx

